---
name: 门诊科室分布
title: 门诊科室分布饼图
category: 流程图模板·饼图
---
pie showData
    title 2026 年 7 月医院门诊科室就诊人次分布，单位人次
    "内科" : 8640
    "儿科" : 6180
    "外科" : 3920
    "妇产科" : 3260
    "口腔科" : 2480
    "皮肤科" : 2180
    "眼科" : 1860
    "耳鼻喉科" : 1520
    "中医科" : 1240
