---
name: 能源结构占比
title: 能源结构占比饼图
category: 流程图模板·饼图
---
pie showData
    title 2026 年上半年园区用电结构占比，单位百分比
    "煤电" : 34
    "光伏" : 22
    "天然气发电" : 18
    "风电" : 14
    "水电" : 8
    "储能放电" : 3
    "外购绿电" : 1
